### ISSUE TITLE
[BUG] SDK is not encoding attestation properly

### ISSUE THREAD

**Issue by orbmis** [Consensys/linea-attestation-registry#558]
For schemas that have datatypes other than string, e.g. `bytes32` values, the attestation payload is not encoded properly, which causes an error when trying to issue the attestation

**Comment by alainncls** [comment]
It seems that this was in fact due to #556: trying to use the wrongly formatted `Relationship` Schema made the SDK fail to encode the payload.
In order to mitigate this issue, we'll improve the way we use the Schema string to encode the payload, to take into account the Schemas that are not "tuples" (without surrounding parenthesis).
