### ISSUE TITLE
[US] As a developer, I want to have a new version of the Modules system

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#574]
As a developer,
I want to have a new version of the Modules system,
So that I benefit from more flexibility and be able to implement more use cases

**Comment by MOZGIII** [comment]
More details here on what `from more flexibility` and `more use cases` are would be great.

<details><summary>Offtopic</summary>
<p>

Just imagine this being an entirety of a description of a task someone received, lol

</p>
</details> 

I got here trying to unwind the motivation behind #562.
This issue is clearly created just to fulfill some formality, not to actually develop in the open - which is a shame.
