### ISSUE TITLE
[BUG] As a user, I want to have a consistent default sorting logic accross all the pages in the explorer

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-attestation-registry#686]
### Issue

Currently we have inconsistent default sorting logic in the explorer:

Some page display Attestations from newest to oldest:
- [default Attestation page](https://explorer.ver.ax/linea/attestations) 

Some others are displaying oldest to newest:
- [Schema detail page](https://explorer.ver.ax/linea/schemas/0x01f031da36192c34057c764239eb77bb6ec8ebfb808f72a7bb172f37a5bec31f)

### Solution

Always sort newest Attestation first by default

**Comment by arthur-remy** [comment]
Has this been released yet?

I notice their is some pages where attestations are sorted from oldest to newest:
* [My attestation page](https://explorer.ver.ax//linea/attestations/my_attestations)
* [Search results](https://explorer.ver.ax/linea/search?search_query=0xc5fd29cC1a1b76ba52873fF943FEDFDD36cF46C6)

Also, this might be a regression but, on those two pages, I'm not able to manually reverse the ordering anymore.

See video here: https://github.com/user-attachments/assets/ac3d5aff-4b29-4312-a827-770661f6b1e2

I let you reopen this ticket or create a new one if the issue is confirmed
